
  const teamBuildingQuestions =[
    "What's your favorite way to spend a lazy Sunday?",
    "Do you have a favorite childhood memory?",
    "What's the most adventurous thing you've ever done?",
    "If you could travel anywhere in the world, where would it be?",
    "What's your go-to comfort food?",
    "Are you a morning person or a night owl?",
    "What's a skill you've always wanted to learn?",
    "Do you have any hidden talents?",
    "What's your favorite type of music?",
    "Do you prefer the mountains or the beach?",
    "What's a book or movie that you could read or watch over and over?",
    "What's your dream car?",
    "Do you have any favorite sports teams?",
    "If you could have dinner with any fictional character, who would it be?",
    "What's your favorite holiday and why?",
    "Do you have a favorite season?",
    "What's the last concert or live performance you attended?",
    "What's your favorite board game?",
    "Are you a cat person or a dog person?",
    "What's the most interesting place you've ever visited?",
    "If you could have any animal as a pet, exotic or not, what would it be?",
    "Do you have a favorite quote or saying?",
    "What's your idea of a perfect day?",
    "What's the last TV show you binge-watched?",
    "If you could have any one wish granted, what would it be?",
    "What's a hobby you've always wanted to pick up?",
    "Do you have a favorite app on your phone?",
    "What's your favorite type of cuisine?",
    "What's your spirit animal?",
    "Do you have any phobias?",
    "If you could time travel, would you go to the past or the future?",
    "What's your favorite childhood cartoon?",
    "Do you have a favorite podcast?",
    "What's your favorite way to exercise?",
    "What's the most beautiful place you've ever been?",
    "If you could meet any historical figure, who would it be?",
    "What's your favorite ice cream flavor?",
    "Do you prefer sweet or savory snacks?",
    "What's your favorite outdoor activity?",
    "If you could have any job for a day, what would it be?",
    "What's your favorite type of art?",
    "Do you have any family traditions?",
    "What's your guilty pleasure TV show?",
    "If you could have a dinner party with any three people (dead or alive), who would they be?",
    "What's your favorite way to de-stress?",
    "Do you have a favorite quote from a movie?",
    "What's the most interesting documentary you've ever watched?",
    "If you could live in any fictional universe, which one would it be?",
    "What's your favorite type of dessert?",
    "Do you have a favorite childhood toy?",
    "What's your preferred mode of transportation?",
    "What's your favorite thing about the city you live in?",
    "If you could have any talent or skill instantly, what would it be?",
    "What's your favorite genre of literature?",
    "Do you have a favorite podcast?",
    "What's your favorite way to stay active?",
    "If you could have dinner with any historical figure, who would it be?",
    "Do you have a favorite board game?",
    "What's the most memorable gift you've ever received?",
    "What's your favorite type of cuisine?",
    "Do you have a favorite spot in nature?",
    "What's the last thing you learned that surprised you?",
    "If you could have any superpower, what would it be?",
    "What's your favorite holiday and how do you celebrate it?",
    "Do you have any favorite quotes?",
    "What's your preferred way to relax after a long day?",
    "If you could learn any language fluently, which would it be?",
    "What's your favorite way to stay fit?",
    "Do you have a favorite genre of music?",
    "What's your favorite childhood TV show?",
    "If you could have any animal as a pet, what would it be?",
    "What's your favorite way to spend a weekend?",
    "Do you have a favorite childhood game?",
    "What's your favorite way to stay connected with friends and family?",
    "If you could have dinner with any fictional character, who would it be?",
    "Do you have a favorite type of cuisine?",
    "What's the most beautiful place you've ever visited?",
    "If you could meet any historical figure, who would it be?",
    "What's your favorite type of art?",
    "Do you have any family traditions?",
    "What's your guilty pleasure TV show?",
    "If you could have a dinner party with any three people (dead or alive), who would they be?",
    "What's your favorite way to de-stress?",
    "Do you have a favorite quote from a movie?",
    "What's the most interesting documentary you've ever watched?",
    "If you could live in any fictional universe, which one would it be?",
    "What's your favorite type of dessert?",
    "Do you have a favorite childhood toy?",
    "What's your preferred mode of transportation?",
    "What's your favorite thing about the city you live in?",
    "If you could have any talent or skill instantly, what would it be?",
    "What's your favorite genre of literature?",
    "Do you have a favorite podcast?",
    "What's your favorite way to stay active?",
    "If you could have dinner with any historical figure, who would it be?",
    "Do you have a favorite board game?",
    "What's the most memorable gift you've ever received?",
    "What's your favorite type of cuisine?",
    "Do you have a favorite spot in nature?",
    "What's the last thing you learned that surprised you?",
    "If you could have any superpower, what would it be?",
    "What's your favorite holiday and how do you celebrate it?",
    "Do you have any favorite quotes?",
    "What's your preferred way to relax after a long day?",
    "If you could learn any language fluently, which would it be?",
    "What's your favorite way to stay fit?",
    "Do you have a favorite genre of music?",
    "What's your favorite childhood TV show?",
    "If you could have any animal as a pet, what would it be?",
    "What's your favorite way to spend a weekend?",
    "Do you have a favorite childhood game?",
    "What's your favorite way to stay connected with friends and family?"
  ];
  export default teamBuildingQuestions;

